### ISSUE TITLE
FontFreeze

### ISSUE THREAD

**Issue by cormullion** [justinpenner/type-design-resources#21]
I discovered this today:

https://mutsuntsai.github.io/fontfreeze/

An online converter that lets you make versions of fonts with various OpenType features frozen on or off. Might be worth a mention...?

**Comment by justinpenner** [comment]
Thanks! I'll see if I can find a place for it in the next update. It's probably not as useful for type designers as it is for people who use type, but the fact that it's running fontTools in the browser is impressive, and since it's MIT-licensed, it might also be useful for foundries who are building customization features into their website. The [Font tools for web development](https://typedesignresources.com/#font-tools-for-web-development) section might be a good home for it.
