### ISSUE TITLE
website offline?

### ISSUE THREAD

**Issue by cormullion** [justinpenner/type-design-resources#35]
I couldn’t reach the site just now 🤔

**Comment by andreirobu** [comment]
It's down for me too.

**Comment by justinpenner** [comment]
Thanks for the heads up! I transferred the domain out of Squarespace Domains (formerly Google Domains) last week. Normally that should be completed in under an hour, or in 24h at most, but Squarespace has apparently been dragging their feet for everyone who's trying to leave.

I tried to set it up so that there would be no downtime, but that didn't work, so I manually fixed the DNS/NS settings just now. It should be back online shortly.

**Comment by justinpenner** [comment]
It's back online on my mobile connection, and it's working when I check through some proxies and DNS checkers. Not yet on my home internet connection, but that one often takes ages to refresh DNS changes. Please report if anyone notices it still isn't working in 24 hours. Thanks!

**Comment by cormullion** [comment]
works fine now! Thanks
